require('dotenv').config();
const path = require('path');

// The app's client ID and secret, which are used to authenticate with the server
const APS_CLIENT_ID = process.env.APS_CLIENT_ID || '';
const APS_CLIENT_SECRET = process.env.APS_CLIENT_SECRET || '';

// The port that the server will listen on
const PORT = process.env.PORT || 8080;

// The Design Automation configuration
const DA_CONFIG = {
    // The name of the bucket that will be used to store the input and output files
    BUCKET_NAME: process.env.APS_BUCKET_NAME || 'my_test_bucketnew',

    // The region that the bucket will be created in
    BUCKET_REGION: process.env.APS_BUCKET_REGION || 'US',

    // The name of the app bundle that will be created
    APP_BUNDLE_NAME: process.env.APS_BUNDLE_APP_NAME || 'my_dynamo_appnew',

    // The nickname of the app, which is used to identify the app in the Design Automation API
    NICKNAME: process.env.APS_NICKNAME || 'my_nicknamenew',

    // The name of the activity that will be created
    ACTIVITY_NAME: process.env.APS_ACTIVITY_NAME || 'my_activity_1new',

    // The alias of the activity, which is used to identify the activity in the Design Automation API
    ACTIVITY_ALIAS: 'default'
};

// The folder where the DA files are stored
const DA_FOLDER = process.env.DA_FOLDER || './da_files';

// The names of the files that are used in the DA process
// BUNDLE_FILE removed - AppBundle files are now uploaded via web interface
const PYTHON_FILE = process.env.APS_PYTHON_FILE || 'pythonDependencies.zip';
const DYN_FILE = process.env.APS_DYN_FILE || 'run.dyn';
const PACKAGES_FILE = process.env.APS_PACKAGES_FILE || 'packages.zip';
const RUN_REQ_FILE = process.env.APS_RUN_REQ_FILE || 'run.json';

// The names of the result files that are generated by the DA process
const RESULT_FILE = process.env.APS_RESULT_FILE || 'result.json';
const RVT_RESULT_FILE = process.env.APS_RVT_RESULT_FILE || 'result.rvt';

// The engine that the DA process will use
const ENGINE = 'Autodesk.Revit+2026';

// Add ENGINE to DA_CONFIG for consistency
DA_CONFIG.ENGINE = ENGINE;

// Base URLs for APS services
const OSS_BASE_URL = 'https://developer.api.autodesk.com/oss/v2';
const DA_BASE_URL = 'https://developer.api.autodesk.com/da/us-east/v3';

// Export the configuration
module.exports = {
    APS_CLIENT_ID,
    APS_CLIENT_SECRET,
    PORT,
    DA_CONFIG,
    DA_FOLDER,
    // BUNDLE_FILE removed
    PYTHON_FILE,
    DYN_FILE,
    PACKAGES_FILE,
    RUN_REQ_FILE,
    RESULT_FILE,
    RVT_RESULT_FILE,
    ENGINE,
    OSS_BASE_URL,
    DA_BASE_URL
}; 